language:       node_js

node_js:
    - "node"
    - "8.6.0"

sudo:           false

git:
    submodules: false

before_install:
- export TZ=Europe/Stockholm

before_script:
    - npm install

script:
    - npm run test

notifications:
    email:      false
